# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: testpilot/echo/v1/echo.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'testpilot/echo/v1/echo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ctestpilot/echo/v1/echo.proto\x12\x11testpilot.echo.v1\".\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06repeat\x18\x02 \x01(\x05\"/\n\x0c\x45\x63hoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06length\x18\x02 \x01(\x05\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1a\n\x0b\x41\x64\x64Response\x12\x0b\n\x03sum\x18\x01 \x01(\x05\x32\x9c\x01\n\x0b\x45\x63hoService\x12G\n\x04\x45\x63ho\x12\x1e.testpilot.echo.v1.EchoRequest\x1a\x1f.testpilot.echo.v1.EchoResponse\x12\x44\n\x03\x41\x64\x64\x12\x1d.testpilot.echo.v1.AddRequest\x1a\x1e.testpilot.echo.v1.AddResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'testpilot.echo.v1.echo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ECHOREQUEST']._serialized_start=51
  _globals['_ECHOREQUEST']._serialized_end=97
  _globals['_ECHORESPONSE']._serialized_start=99
  _globals['_ECHORESPONSE']._serialized_end=146
  _globals['_ADDREQUEST']._serialized_start=148
  _globals['_ADDREQUEST']._serialized_end=182
  _globals['_ADDRESPONSE']._serialized_start=184
  _globals['_ADDRESPONSE']._serialized_end=210
  _globals['_ECHOSERVICE']._serialized_start=213
  _globals['_ECHOSERVICE']._serialized_end=369
# @@protoc_insertion_point(module_scope)
