# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from testpilot.copilot.v1 import copilot_pb2 as testpilot_dot_copilot_dot_v1_dot_copilot__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in testpilot/copilot/v1/copilot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CopilotToolServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListProjects = channel.unary_unary(
                '/testpilot.copilot.v1.CopilotToolService/ListProjects',
                request_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListProjectsRequest.SerializeToString,
                response_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListProjectsResponse.FromString,
                _registered_method=True)
        self.ListApis = channel.unary_unary(
                '/testpilot.copilot.v1.CopilotToolService/ListApis',
                request_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListApisRequest.SerializeToString,
                response_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListApisResponse.FromString,
                _registered_method=True)
        self.GetApi = channel.unary_unary(
                '/testpilot.copilot.v1.CopilotToolService/GetApi',
                request_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.GetApiRequest.SerializeToString,
                response_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.GetApiResponse.FromString,
                _registered_method=True)
        self.ListEnvironments = channel.unary_unary(
                '/testpilot.copilot.v1.CopilotToolService/ListEnvironments',
                request_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListEnvironmentsRequest.SerializeToString,
                response_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListEnvironmentsResponse.FromString,
                _registered_method=True)
        self.ListTestCases = channel.unary_unary(
                '/testpilot.copilot.v1.CopilotToolService/ListTestCases',
                request_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListTestCasesRequest.SerializeToString,
                response_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListTestCasesResponse.FromString,
                _registered_method=True)
        self.GetTestCase = channel.unary_unary(
                '/testpilot.copilot.v1.CopilotToolService/GetTestCase',
                request_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.GetTestCaseRequest.SerializeToString,
                response_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.GetTestCaseResponse.FromString,
                _registered_method=True)
        self.QuerySchema = channel.unary_unary(
                '/testpilot.copilot.v1.CopilotToolService/QuerySchema',
                request_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.QuerySchemaRequest.SerializeToString,
                response_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.QuerySchemaResponse.FromString,
                _registered_method=True)
        self.ListRuns = channel.unary_unary(
                '/testpilot.copilot.v1.CopilotToolService/ListRuns',
                request_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListRunsRequest.SerializeToString,
                response_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListRunsResponse.FromString,
                _registered_method=True)
        self.GetRun = channel.unary_unary(
                '/testpilot.copilot.v1.CopilotToolService/GetRun',
                request_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.GetRunRequest.SerializeToString,
                response_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.GetRunResponse.FromString,
                _registered_method=True)
        self.QueryCoverage = channel.unary_unary(
                '/testpilot.copilot.v1.CopilotToolService/QueryCoverage',
                request_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.QueryCoverageRequest.SerializeToString,
                response_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.QueryCoverageResponse.FromString,
                _registered_method=True)
        self.QueryApiDirectory = channel.unary_unary(
                '/testpilot.copilot.v1.CopilotToolService/QueryApiDirectory',
                request_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.QueryApiDirectoryRequest.SerializeToString,
                response_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.QueryApiDirectoryResponse.FromString,
                _registered_method=True)
        self.CheckVariableRefs = channel.unary_unary(
                '/testpilot.copilot.v1.CopilotToolService/CheckVariableRefs',
                request_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CheckVariableRefsRequest.SerializeToString,
                response_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CheckVariableRefsResponse.FromString,
                _registered_method=True)
        self.CreateProject = channel.unary_unary(
                '/testpilot.copilot.v1.CopilotToolService/CreateProject',
                request_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CreateProjectRequest.SerializeToString,
                response_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CreateProjectResponse.FromString,
                _registered_method=True)
        self.CreateApi = channel.unary_unary(
                '/testpilot.copilot.v1.CopilotToolService/CreateApi',
                request_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CreateApiRequest.SerializeToString,
                response_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CreateApiResponse.FromString,
                _registered_method=True)
        self.UpdateApi = channel.unary_unary(
                '/testpilot.copilot.v1.CopilotToolService/UpdateApi',
                request_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.UpdateApiRequest.SerializeToString,
                response_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.UpdateApiResponse.FromString,
                _registered_method=True)
        self.CreateTestCase = channel.unary_unary(
                '/testpilot.copilot.v1.CopilotToolService/CreateTestCase',
                request_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CreateTestCaseRequest.SerializeToString,
                response_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CreateTestCaseResponse.FromString,
                _registered_method=True)
        self.CreateTestPlan = channel.unary_unary(
                '/testpilot.copilot.v1.CopilotToolService/CreateTestPlan',
                request_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CreateTestPlanRequest.SerializeToString,
                response_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CreateTestPlanResponse.FromString,
                _registered_method=True)
        self.ImportOpenApi = channel.unary_unary(
                '/testpilot.copilot.v1.CopilotToolService/ImportOpenApi',
                request_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ImportOpenApiRequest.SerializeToString,
                response_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ImportOpenApiResponse.FromString,
                _registered_method=True)
        self.ApplyOpenApiDiff = channel.unary_unary(
                '/testpilot.copilot.v1.CopilotToolService/ApplyOpenApiDiff',
                request_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ApplyOpenApiDiffRequest.SerializeToString,
                response_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ApplyOpenApiDiffResponse.FromString,
                _registered_method=True)
        self.TriggerRun = channel.unary_unary(
                '/testpilot.copilot.v1.CopilotToolService/TriggerRun',
                request_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.TriggerRunRequest.SerializeToString,
                response_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.TriggerRunResponse.FromString,
                _registered_method=True)
        self.TriggerStress = channel.unary_unary(
                '/testpilot.copilot.v1.CopilotToolService/TriggerStress',
                request_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.TriggerStressRequest.SerializeToString,
                response_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.TriggerStressResponse.FromString,
                _registered_method=True)


class CopilotToolServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListProjects(self, request, context):
        """---- 只读工具（免审批） ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListApis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetApi(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEnvironments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTestCases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTestCase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuerySchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryCoverage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryApiDirectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckVariableRefs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProject(self, request, context):
        """---- 写工具（默认 HITL 审批） ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateApi(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateApi(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTestCase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTestPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportOpenApi(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyOpenApiDiff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerRun(self, request, context):
        """---- 触发工具（默认 HITL 审批） ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerStress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CopilotToolServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProjects,
                    request_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListProjectsRequest.FromString,
                    response_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListProjectsResponse.SerializeToString,
            ),
            'ListApis': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApis,
                    request_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListApisRequest.FromString,
                    response_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListApisResponse.SerializeToString,
            ),
            'GetApi': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApi,
                    request_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.GetApiRequest.FromString,
                    response_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.GetApiResponse.SerializeToString,
            ),
            'ListEnvironments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEnvironments,
                    request_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListEnvironmentsRequest.FromString,
                    response_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListEnvironmentsResponse.SerializeToString,
            ),
            'ListTestCases': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTestCases,
                    request_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListTestCasesRequest.FromString,
                    response_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListTestCasesResponse.SerializeToString,
            ),
            'GetTestCase': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTestCase,
                    request_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.GetTestCaseRequest.FromString,
                    response_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.GetTestCaseResponse.SerializeToString,
            ),
            'QuerySchema': grpc.unary_unary_rpc_method_handler(
                    servicer.QuerySchema,
                    request_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.QuerySchemaRequest.FromString,
                    response_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.QuerySchemaResponse.SerializeToString,
            ),
            'ListRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRuns,
                    request_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListRunsRequest.FromString,
                    response_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListRunsResponse.SerializeToString,
            ),
            'GetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRun,
                    request_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.GetRunRequest.FromString,
                    response_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.GetRunResponse.SerializeToString,
            ),
            'QueryCoverage': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryCoverage,
                    request_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.QueryCoverageRequest.FromString,
                    response_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.QueryCoverageResponse.SerializeToString,
            ),
            'QueryApiDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryApiDirectory,
                    request_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.QueryApiDirectoryRequest.FromString,
                    response_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.QueryApiDirectoryResponse.SerializeToString,
            ),
            'CheckVariableRefs': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckVariableRefs,
                    request_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CheckVariableRefsRequest.FromString,
                    response_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CheckVariableRefsResponse.SerializeToString,
            ),
            'CreateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProject,
                    request_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CreateProjectRequest.FromString,
                    response_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CreateProjectResponse.SerializeToString,
            ),
            'CreateApi': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateApi,
                    request_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CreateApiRequest.FromString,
                    response_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CreateApiResponse.SerializeToString,
            ),
            'UpdateApi': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateApi,
                    request_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.UpdateApiRequest.FromString,
                    response_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.UpdateApiResponse.SerializeToString,
            ),
            'CreateTestCase': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTestCase,
                    request_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CreateTestCaseRequest.FromString,
                    response_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CreateTestCaseResponse.SerializeToString,
            ),
            'CreateTestPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTestPlan,
                    request_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CreateTestPlanRequest.FromString,
                    response_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CreateTestPlanResponse.SerializeToString,
            ),
            'ImportOpenApi': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportOpenApi,
                    request_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ImportOpenApiRequest.FromString,
                    response_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ImportOpenApiResponse.SerializeToString,
            ),
            'ApplyOpenApiDiff': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyOpenApiDiff,
                    request_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ApplyOpenApiDiffRequest.FromString,
                    response_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ApplyOpenApiDiffResponse.SerializeToString,
            ),
            'TriggerRun': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerRun,
                    request_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.TriggerRunRequest.FromString,
                    response_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.TriggerRunResponse.SerializeToString,
            ),
            'TriggerStress': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerStress,
                    request_deserializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.TriggerStressRequest.FromString,
                    response_serializer=testpilot_dot_copilot_dot_v1_dot_copilot__pb2.TriggerStressResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'testpilot.copilot.v1.CopilotToolService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('testpilot.copilot.v1.CopilotToolService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CopilotToolService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testpilot.copilot.v1.CopilotToolService/ListProjects',
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListProjectsRequest.SerializeToString,
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListProjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListApis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testpilot.copilot.v1.CopilotToolService/ListApis',
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListApisRequest.SerializeToString,
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListApisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetApi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testpilot.copilot.v1.CopilotToolService/GetApi',
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.GetApiRequest.SerializeToString,
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.GetApiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEnvironments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testpilot.copilot.v1.CopilotToolService/ListEnvironments',
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListEnvironmentsRequest.SerializeToString,
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListEnvironmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTestCases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testpilot.copilot.v1.CopilotToolService/ListTestCases',
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListTestCasesRequest.SerializeToString,
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListTestCasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTestCase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testpilot.copilot.v1.CopilotToolService/GetTestCase',
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.GetTestCaseRequest.SerializeToString,
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.GetTestCaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuerySchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testpilot.copilot.v1.CopilotToolService/QuerySchema',
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.QuerySchemaRequest.SerializeToString,
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.QuerySchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testpilot.copilot.v1.CopilotToolService/ListRuns',
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListRunsRequest.SerializeToString,
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ListRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testpilot.copilot.v1.CopilotToolService/GetRun',
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.GetRunRequest.SerializeToString,
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.GetRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryCoverage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testpilot.copilot.v1.CopilotToolService/QueryCoverage',
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.QueryCoverageRequest.SerializeToString,
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.QueryCoverageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryApiDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testpilot.copilot.v1.CopilotToolService/QueryApiDirectory',
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.QueryApiDirectoryRequest.SerializeToString,
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.QueryApiDirectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckVariableRefs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testpilot.copilot.v1.CopilotToolService/CheckVariableRefs',
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CheckVariableRefsRequest.SerializeToString,
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CheckVariableRefsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testpilot.copilot.v1.CopilotToolService/CreateProject',
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CreateProjectRequest.SerializeToString,
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CreateProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateApi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testpilot.copilot.v1.CopilotToolService/CreateApi',
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CreateApiRequest.SerializeToString,
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CreateApiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateApi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testpilot.copilot.v1.CopilotToolService/UpdateApi',
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.UpdateApiRequest.SerializeToString,
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.UpdateApiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTestCase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testpilot.copilot.v1.CopilotToolService/CreateTestCase',
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CreateTestCaseRequest.SerializeToString,
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CreateTestCaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTestPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testpilot.copilot.v1.CopilotToolService/CreateTestPlan',
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CreateTestPlanRequest.SerializeToString,
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.CreateTestPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportOpenApi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testpilot.copilot.v1.CopilotToolService/ImportOpenApi',
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ImportOpenApiRequest.SerializeToString,
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ImportOpenApiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyOpenApiDiff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testpilot.copilot.v1.CopilotToolService/ApplyOpenApiDiff',
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ApplyOpenApiDiffRequest.SerializeToString,
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.ApplyOpenApiDiffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testpilot.copilot.v1.CopilotToolService/TriggerRun',
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.TriggerRunRequest.SerializeToString,
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.TriggerRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerStress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testpilot.copilot.v1.CopilotToolService/TriggerStress',
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.TriggerStressRequest.SerializeToString,
            testpilot_dot_copilot_dot_v1_dot_copilot__pb2.TriggerStressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
