# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from testpilot.worker.v1 import worker_pb2 as testpilot_dot_worker_dot_v1_dot_worker__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in testpilot/worker/v1/worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub:
    """Worker 生命周期：启动 -> Connect(register) -> 双向流（任务/心跳/结果） -> 断开。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/testpilot.worker.v1.WorkerService/Connect',
                request_serializer=testpilot_dot_worker_dot_v1_dot_worker__pb2.WorkerEvent.SerializeToString,
                response_deserializer=testpilot_dot_worker_dot_v1_dot_worker__pb2.SchedulerCommand.FromString,
                _registered_method=True)


class WorkerServiceServicer:
    """Worker 生命周期：启动 -> Connect(register) -> 双向流（任务/心跳/结果） -> 断开。
    """

    def Connect(self, request_iterator, context):
        """Worker 建立长连接。连接后第一条 WorkerEvent 必须是 register。
        之后 Worker 上行 heartbeat/进度/日志/结果/指标，Scheduler 下行 task/cancel/config。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=testpilot_dot_worker_dot_v1_dot_worker__pb2.WorkerEvent.FromString,
                    response_serializer=testpilot_dot_worker_dot_v1_dot_worker__pb2.SchedulerCommand.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'testpilot.worker.v1.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('testpilot.worker.v1.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService:
    """Worker 生命周期：启动 -> Connect(register) -> 双向流（任务/心跳/结果） -> 断开。
    """

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/testpilot.worker.v1.WorkerService/Connect',
            testpilot_dot_worker_dot_v1_dot_worker__pb2.WorkerEvent.SerializeToString,
            testpilot_dot_worker_dot_v1_dot_worker__pb2.SchedulerCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
