package grpcserver_test

import (
	"context"
	"testing"

	commonv1 "github.com/testpilot/testpilot/gen/common/v1"
	workerv1 "github.com/testpilot/testpilot/gen/worker/v1"
	"github.com/testpilot/testpilot/internal/dispatch"
	"github.com/testpilot/testpilot/internal/grpcserver"
	"github.com/testpilot/testpilot/internal/quota"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

func newWorkerClient(t *testing.T) (workerv1.WorkerServiceClient, *dispatch.Dispatcher) {
	t.Helper()
	disp := dispatch.New(openTestDB(t))
	conn := bufConn(t, func(srv *grpc.Server) {
		workerv1.RegisterWorkerServiceServer(srv, grpcserver.NewWorkerService(disp))
	})
	return workerv1.NewWorkerServiceClient(conn), disp
}

func registerEvent(reg *workerv1.RegisterRequest) *workerv1.WorkerEvent {
	return &workerv1.WorkerEvent{Event: &workerv1.WorkerEvent_Register{Register: reg}}
}

func findWorker(disp *dispatch.Dispatcher, id string) *dispatch.Worker {
	for _, w := range disp.Workers() {
		if w.ID == id {
			return w
		}
	}
	return nil
}

// Connect 主流程：Register 事件注册 → 心跳改负载 → Result 事件不断流 → 关流注销。
func TestWorkerConnectLifecycle(t *testing.T) {
	cli, disp := newWorkerClient(t)
	stream, err := cli.Connect(context.Background())
	if err != nil {
		t.Fatal(err)
	}

	// 首帧 Register：capabilities/tenant/max_concurrency 转换后进入 Dispatcher。
	err = stream.Send(registerEvent(&workerv1.RegisterRequest{
		WorkerId:       "w1",
		WorkerName:     "edge-1",
		Capabilities:   []commonv1.Capability{commonv1.Capability_CAPABILITY_FUNCTIONAL, commonv1.Capability_CAPABILITY_STRESS},
		TenantId:       7,
		MaxConcurrency: 4,
		Tags:           []string{"gpu", "cn"},
		SdkVersion:     "1.2.3",
	}))
	if err != nil {
		t.Fatal(err)
	}
	waitFor(t, "worker registered", func() bool { return findWorker(disp, "w1") != nil })
	w := findWorker(disp, "w1")
	if w.Name != "edge-1" || w.TenantID != 7 || w.MaxConcurrency != 4 || w.SDKVersion != "1.2.3" {
		t.Fatalf("worker fields mismatch: %+v", w)
	}
	if len(w.Tags) != 2 || w.Tags[0] != "gpu" || w.Tags[1] != "cn" {
		t.Fatalf("tags mismatch: %v", w.Tags)
	}
	if len(w.Capabilities) != 2 ||
		w.Capabilities[0] != int32(commonv1.Capability_CAPABILITY_FUNCTIONAL) ||
		w.Capabilities[1] != int32(commonv1.Capability_CAPABILITY_STRESS) {
		t.Fatalf("capabilities mismatch: %v", w.Capabilities)
	}
	if got := w.Load(); got != 0 {
		t.Fatalf("initial load=%d, want 0", got)
	}

	// 心跳事件 → SetLoad(current_concurrency)。
	if err := stream.Send(&workerv1.WorkerEvent{Event: &workerv1.WorkerEvent_Heartbeat{
		Heartbeat: &workerv1.Heartbeat{CurrentConcurrency: 3},
	}}); err != nil {
		t.Fatal(err)
	}
	waitFor(t, "load=3 after heartbeat", func() bool { return findWorker(disp, "w1").Load() == 3 })

	// Result 事件（未知 run，幂等丢弃）不应中断流；随后心跳仍生效。
	if err := stream.Send(&workerv1.WorkerEvent{Event: &workerv1.WorkerEvent_TaskResult{
		TaskResult: &workerv1.TaskResult{RunId: "999999", Status: commonv1.RunStatus_RUN_STATUS_PASSED},
	}}); err != nil {
		t.Fatal(err)
	}
	if err := stream.Send(&workerv1.WorkerEvent{Event: &workerv1.WorkerEvent_Heartbeat{
		Heartbeat: &workerv1.Heartbeat{CurrentConcurrency: 1},
	}}); err != nil {
		t.Fatal(err)
	}
	waitFor(t, "load=1 after result+heartbeat", func() bool { return findWorker(disp, "w1").Load() == 1 })

	// 关流 → io.EOF → worker 注销。
	if err := stream.CloseSend(); err != nil {
		t.Fatal(err)
	}
	waitFor(t, "worker unregistered after stream close", func() bool { return len(disp.Workers()) == 0 })
}

// 首帧非 Register → InvalidArgument。
func TestWorkerConnectFirstFrameMustBeRegister(t *testing.T) {
	cli, disp := newWorkerClient(t)
	stream, err := cli.Connect(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if err := stream.Send(&workerv1.WorkerEvent{Event: &workerv1.WorkerEvent_Heartbeat{
		Heartbeat: &workerv1.Heartbeat{CurrentConcurrency: 1},
	}}); err != nil {
		t.Fatal(err)
	}
	if _, err := stream.Recv(); status.Code(err) != codes.InvalidArgument {
		t.Fatalf("want InvalidArgument, got %v", err)
	}
	if got := len(disp.Workers()); got != 0 {
		t.Fatalf("workers=%d, want 0", got)
	}
}

// worker_id 为空时服务端自动生成（w- 前缀）。
func TestWorkerConnectAutoGeneratedID(t *testing.T) {
	cli, disp := newWorkerClient(t)
	stream, err := cli.Connect(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	defer stream.CloseSend()
	if err := stream.Send(registerEvent(&workerv1.RegisterRequest{
		Capabilities: []commonv1.Capability{commonv1.Capability_CAPABILITY_FUNCTIONAL},
	})); err != nil {
		t.Fatal(err)
	}
	waitFor(t, "auto-id worker registered", func() bool { return len(disp.Workers()) == 1 })
	if id := disp.Workers()[0].ID; id == "" {
		t.Fatal("worker id should be auto-generated")
	}
}

// 租户专属 Worker 超 worker_slots 配额 → ResourceExhausted，且不占用槽位。
func TestWorkerConnectQuotaRejected(t *testing.T) {
	// 需要给同一个库设配额，本用例内联搭建而非 newWorkerClient。
	d := openTestDB(t)
	if err := quota.Set(d, 9, quota.MetricWorkerSlots, 1); err != nil {
		t.Fatal(err)
	}
	disp2 := dispatch.New(d)
	conn := bufConn(t, func(srv *grpc.Server) {
		workerv1.RegisterWorkerServiceServer(srv, grpcserver.NewWorkerService(disp2))
	})
	cli2 := workerv1.NewWorkerServiceClient(conn)

	// 第一个租户 9 Worker 注册成功。
	s1, err := cli2.Connect(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	defer s1.CloseSend()
	if err := s1.Send(registerEvent(&workerv1.RegisterRequest{
		WorkerId:     "q1",
		TenantId:     9,
		Capabilities: []commonv1.Capability{commonv1.Capability_CAPABILITY_FUNCTIONAL},
	})); err != nil {
		t.Fatal(err)
	}
	waitFor(t, "q1 registered", func() bool { return findWorker(disp2, "q1") != nil })

	// 第二个同租户 Worker 超配额 → ResourceExhausted。
	s2, err := cli2.Connect(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if err := s2.Send(registerEvent(&workerv1.RegisterRequest{
		WorkerId:     "q2",
		TenantId:     9,
		Capabilities: []commonv1.Capability{commonv1.Capability_CAPABILITY_FUNCTIONAL},
	})); err != nil {
		t.Fatal(err)
	}
	if _, err := s2.Recv(); status.Code(err) != codes.ResourceExhausted {
		t.Fatalf("want ResourceExhausted, got %v", err)
	}
	if got := len(disp2.Workers()); got != 1 {
		t.Fatalf("workers=%d, want 1 (rejected worker must not occupy a slot)", got)
	}

	// 共享 Worker（tenant 0）不受 worker_slots 限制。
	s3, err := cli2.Connect(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	defer s3.CloseSend()
	if err := s3.Send(registerEvent(&workerv1.RegisterRequest{
		WorkerId:     "shared",
		Capabilities: []commonv1.Capability{commonv1.Capability_CAPABILITY_FUNCTIONAL},
	})); err != nil {
		t.Fatal(err)
	}
	waitFor(t, "shared worker registered", func() bool { return findWorker(disp2, "shared") != nil })
}
